name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Run ESLint
              run: npm run lint

            - name: Run unit tests
              run: npm test

            - name: Start server and run E2E tests
              run: |
                  npm start &
                  npx wait-on http://localhost:3009
                  npm run test:e2e
                  kill $(lsof -ti :3009)
              env:
                  PORT: 3009
                  CI: true
                  NODE_ENV: test
                  SENTRY_DSN: ""
