name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Install Playwright browsers
              run: npx playwright install --with-deps

            - name: Run ESLint
              run: npm run lint

            - name: Run unit tests
              run: npm test

            - name: Start server
              run: npm start &
              env:
                  PORT: 3009

            - name: Wait for server to start
              run: sleep 5

            - name: Kill any process using port 3009
              run: |
                  sudo lsof -ti :3009 | xargs -r sudo kill -9

            - name: Run E2E tests
              run: npm run test:e2e
              env:
                  CI: true
                  SENTRY_DSN: "" # Désactive Sentry pour les tests
